name: HTML5 Validation Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate_html5:
    runs-on: ubuntu-latest
    name: Validate HTML5

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: HTML5 Validator
      uses: Cyb3r-Jak3/html5validator-action@v7.2.0
