name: Jekyll site CI

on:
  push:name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

stages:
  - lint
  - test
  - build
  - jekyll_build

lint:
  stage: lint
  script:
    - eslint .

test:
  stage: test
  script:
    - npm install
    - npm install --save-dev jest
    - npm test

build:
  stage: build
  script:
    - webpack

jekyll_build:
  stage: jekyll_build
  runs-on: ubuntu-latest
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
          -v ${{ github.workspace }}:/srv/jekyll \
          -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

before_script:
  - echo "Check if tests passed before allowing merge"
after_script:
  - exit 0

only:
  - merge_requests

    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
