name: SonarCloud analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          # Unique keys of your project and organization. You can find them in SonarCloud > Information (bottom-left menu)
          projectKey: ''
          organization: ''
          # Exclude files of unwanted languages
          exclusions: '**/*.java,**/*.ts,**/*.tsx,**/*.py,**/*.cs'
          # Include only files of desired languages
          inclusions: '**/*.php,**/*.html,**/*.css,**/*.js,**/*.jsx,**/*.vue'
