name: HTML Syntax Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  html-syntax-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install htmlhint
        run: npm install -g htmlhint

      - name: HTML Syntax Check
        run: htmlhint "**/*.html"
